# Generated by Django 4.2.9 on 2024-12-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialsModel',
        ),
    ]
