# Generated by Django 4.2.9 on 2025-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0002_create_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupportModel',
            fields=[
                ('requester_username', models.CharField(max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_request_type', models.CharField(max_length=150)),
                ('ticket_title', models.CharField(max_length=150)),
                ('ticket_description', models.TextField()),
                ('ticket_attachments', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('ticket_status', models.CharField(max_length=150)),
                ('ticket_assigned_to', models.CharField(max_length=150)),
                ('ticket_created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_comments', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
