# Generated by Django 3.1.5 on 2023-12-01 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamehive', '0002_testimonialsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsmodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='testimonialsmodel',
            name='surname',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
