# Generated by Django 3.1.5 on 2023-12-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0003_auto_20231201_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
