# Generated by Django 4.2.9 on 2024-12-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0003_testimonialsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialsModel',
        ),
    ]
