# Generated by Django 4.2.9 on 2024-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0004_delete_testimonialsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_of_testimonial', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
