# Generated by Django 3.1.5 on 2023-12-04 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamehive', '0005_updatepersonaldetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdatePersonalDetails',
            new_name='PersonalDetails',
        ),
    ]
