# Generated by Django 3.1.5 on 2023-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehive', '0006_auto_20231204_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuserprofile',
            old_name='current_score',
            new_name='current_score_guess_number_game',
        ),
        migrations.AddField(
            model_name='gameuserprofile',
            name='current_score_rps',
            field=models.IntegerField(default=0),
        ),
    ]
